// Gemini Vision API로 Action Map PNG에서 올챙이(tadpole) 좌표 추출
// 1장의 이미지에서 carries/passes/crosses 3개 섹션을 한 번에 추출

import { getGeminiClient } from "./gemini-client";
import { logError, logInfo, logWarn } from "./logger";
import type { ParsedActionLine } from "./types";
import { waitForVisionSlot } from "./vision-rate-limiter";

/** Vision API 응답에서 파싱할 단일 라인 */
interface RawVisionLine {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  color: "pink" | "mint" | "black";
  circle_size?: "small" | "medium" | "large";
}

/** 3개 타입 통합 Vision API 응답 스키마 */
interface AllActionsVisionResponse {
  carries: RawVisionLine[];
  passes: RawVisionLine[];
  crosses: RawVisionLine[];
}

/** 3개 타입 통합 추출 결과 */
export interface AllActionLines {
  carries: ParsedActionLine[];
  passes: ParsedActionLine[];
  crosses: ParsedActionLine[];
}

/** 재시도 가능한 에러인지 판별 (503, 429) */
function isRetryableError(error: unknown): boolean {
  if (!(error instanceof Error)) return false;
  const msg = error.message;
  return (
    msg.includes("503") ||
    msg.includes("429") ||
    msg.includes("RESOURCE_EXHAUSTED")
  );
}

/** 에러에서 retryDelay 추출 (429 응답에 포함될 수 있음) */
function extractRetryDelay(error: unknown): number | null {
  if (!(error instanceof Error)) return null;
  const match = error.message.match(/retry.*?(\d+)\s*s/i);
  return match ? parseInt(match[1]!, 10) * 1000 : null;
}

/** 지수 백오프 재시도 래퍼 */
async function withRetry<T>(
  fn: () => Promise<T>,
  maxRetries: number = 3,
  baseDelayMs: number = 10_000,
): Promise<T> {
  let lastError: unknown;
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      return await fn();
    } catch (error) {
      lastError = error;
      if (attempt >= maxRetries || !isRetryableError(error)) {
        throw error;
      }
      // 429 응답의 retryDelay 우선, 없으면 지수 백오프
      const retryDelay = extractRetryDelay(error);
      const delay = retryDelay ?? baseDelayMs * Math.pow(2, attempt);
      logWarn(
        `  Vision API 재시도 ${attempt + 1}/${maxRetries} (${Math.ceil(delay / 1000)}초 후): ${error instanceof Error ? error.message : "unknown"}`,
      );
      await new Promise((resolve) => setTimeout(resolve, delay));
    }
  }
  throw lastError;
}

/** 피치 좌표 유효성 검증 */
function isValidCoordinate(x: number, y: number): boolean {
  return x >= 0 && x <= 105 && y >= 0 && y <= 68;
}

/** circle_size → xT 근사값 매핑 */
function circleToXt(size?: "small" | "medium" | "large"): number | undefined {
  switch (size) {
    case "large":
      return 0.05;
    case "medium":
      return 0.025;
    case "small":
      return 0.01;
    default:
      return undefined;
  }
}

/** 3개 섹션 통합 프롬프트 */
function buildAllActionsPrompt(): string {
  return `You are analyzing a football (soccer) action map image generated by ScoutLab.

## Image Layout
The image contains THREE separate pitch maps arranged SIDE BY SIDE (horizontally):
1. LEFT section: CARRIES (dribbles)
2. MIDDLE section: PASSES
3. RIGHT section: CROSSES

Each section shows a football pitch in PORTRAIT (vertical) orientation on a white background.
Pitch markings (touchlines, penalty boxes, center circle) are drawn as very faint light-gray lines.
There is a legend bar at the very bottom of the image.

## Pitch Orientation (PORTRAIT — applies to EACH section independently)
- The ATTACKING goal is at the TOP of each pitch
- The DEFENSIVE goal is at the BOTTOM of each pitch
- Left touchline on the LEFT, right touchline on the RIGHT

## Coordinate System
We use a standard 105m × 68m coordinate system:
- x-axis = pitch LENGTH (0 to 105). x=0 is at the BOTTOM (defensive goal line), x=105 is at the TOP (attacking goal line)
- y-axis = pitch WIDTH (0 to 68). y=0 is the LEFT touchline, y=68 is the RIGHT touchline

So visually in the portrait image:
- Moving UP in the image = increasing x (toward attacking goal)
- Moving RIGHT in the image = increasing y (toward right touchline)

## Landmark Anchors (use these to calibrate coordinates)
- Center circle: center at (52.5, 34) — visually at the CENTER of each pitch
- Bottom (defensive) penalty box: x=0 to x=16.5, y=13.84 to y=54.16 — faint rectangle at BOTTOM
- Top (attacking) penalty box: x=88.5 to x=105, y=13.84 to y=54.16 — faint rectangle at TOP
- Bottom 6-yard box: x=0 to x=5.5, y=24.84 to y=43.16
- Top 6-yard box: x=99.5 to x=105, y=24.84 to y=43.16
- Penalty spots: (11, 34) near bottom, (94, 34) near top

## Tadpole Structure
Each tadpole consists of:
1. A LINE: the thick/dot end = start point (ball origin), the thin/tapered end = end point (ball destination)
2. A CIRCLE at the start point: size proportional to xT (expected threat) value

## Color Classification
- PINK/MAGENTA lines = "progressive" (forward-moving actions)
- CYAN/TEAL lines = "threatening" (xT > 0.02)
- BLACK/DARK GRAY lines = regular (neither progressive nor threatening)
Note: most lines are pink or cyan. Black/gray lines are rare and faint.

## Task
Extract ALL visible tadpole lines from ALL THREE sections. For each line:
1. Determine which section it belongs to (LEFT=carries, MIDDLE=passes, RIGHT=crosses)
2. Estimate start (x1,y1) and end (x2,y2) coordinates in pitch meters using the coordinate system above
3. Classify the color as "pink", "mint", or "black"
4. Estimate the circle size as "small", "medium", or "large"

IMPORTANT:
- Each section has its OWN coordinate system. Do NOT mix lines between sections.
- Remember: UP in image = higher x, RIGHT in image = higher y.
- A "progressive" (pink) carry/pass typically goes UPWARD (x2 > x1), toward the attacking goal.

Round coordinates to 1 decimal place.

Respond with ONLY valid JSON in this exact format (no markdown, no explanation):
{"carries":[{"x1":30.5,"y1":45.2,"x2":55.0,"y2":40.1,"color":"pink","circle_size":"medium"}],"passes":[...],"crosses":[...]}

If a section has no visible tadpoles, use an empty array for that type.`;
}

/** RawVisionLine[] → ParsedActionLine[] 변환 + 유효성 검증 */
function parseRawLines(rawLines: RawVisionLine[]): ParsedActionLine[] {
  const validLines: ParsedActionLine[] = [];
  for (const line of rawLines) {
    if (
      typeof line.x1 !== "number" ||
      typeof line.y1 !== "number" ||
      typeof line.x2 !== "number" ||
      typeof line.y2 !== "number"
    ) {
      continue;
    }

    if (
      !isValidCoordinate(line.x1, line.y1) ||
      !isValidCoordinate(line.x2, line.y2)
    ) {
      continue;
    }

    validLines.push({
      x1: Math.round(line.x1 * 10) / 10,
      y1: Math.round(line.y1 * 10) / 10,
      x2: Math.round(line.x2 * 10) / 10,
      y2: Math.round(line.y2 * 10) / 10,
      progressive: line.color === "pink",
      threatening: line.color === "mint",
      xt: circleToXt(line.circle_size),
    });
  }
  return validLines;
}

/** PNG Buffer → Gemini Vision API 1회 호출 → 3개 타입 동시 추출 */
export async function extractAllActionLinesFromImage(
  imageBuffer: Buffer,
): Promise<AllActionLines> {
  const emptyResult: AllActionLines = { carries: [], passes: [], crosses: [] };
  const client = getGeminiClient();
  const base64 = imageBuffer.toString("base64");

  await waitForVisionSlot();

  try {
    const response = await withRetry(async () => {
      return client.models.generateContent({
        model: "gemini-2.5-flash",
        config: {
          // thinking 비활성화: JSON-only 응답에 사고 과정이 섞이는 것 방지
          thinkingConfig: { thinkingBudget: 0 },
          // JSON 전용 출력 (마크다운 코드블록 방지)
          responseMimeType: "application/json",
          maxOutputTokens: 65536,
        },
        contents: [
          {
            role: "user",
            parts: [
              {
                inlineData: {
                  mimeType: "image/png",
                  data: base64,
                },
              },
              {
                text: buildAllActionsPrompt(),
              },
            ],
          },
        ],
      });
    });

    // 텍스트 응답 추출
    const rawText = response.text?.trim();
    if (!rawText) {
      logWarn(`Vision API 응답에 텍스트 없음`);
      return emptyResult;
    }

    // JSON 파싱
    let parsed: AllActionsVisionResponse;
    try {
      parsed = JSON.parse(rawText) as AllActionsVisionResponse;
    } catch {
      // 마크다운 코드블록 안의 JSON 추출 시도
      const codeBlockMatch = rawText.match(
        /```(?:json)?\s*(\{[\s\S]*\})\s*```/,
      );
      if (codeBlockMatch) {
        try {
          parsed = JSON.parse(codeBlockMatch[1]!) as AllActionsVisionResponse;
        } catch {
          logError(
            `Vision API 코드블록 JSON 파싱 실패: ${rawText.slice(0, 300)}`,
            null,
          );
          return emptyResult;
        }
      } else {
        // "carries" 키를 포함하는 JSON 객체 찾기 (thinking 텍스트 무시)
        const jsonMatch = rawText.match(/\{"carries"\s*:\s*\[[\s\S]*\}/);
        if (jsonMatch) {
          try {
            parsed = JSON.parse(jsonMatch[0]) as AllActionsVisionResponse;
          } catch {
            logError(
              `Vision API 응답 JSON 파싱 실패: ${rawText.slice(0, 300)}`,
              null,
            );
            return emptyResult;
          }
        } else {
          logError(
            `Vision API 응답에서 JSON 찾기 실패: ${rawText.slice(0, 300)}`,
            null,
          );
          return emptyResult;
        }
      }
    }

    // 각 타입별 파싱 + 유효성 검증
    const result: AllActionLines = {
      carries: Array.isArray(parsed.carries)
        ? parseRawLines(parsed.carries)
        : [],
      passes: Array.isArray(parsed.passes) ? parseRawLines(parsed.passes) : [],
      crosses: Array.isArray(parsed.crosses)
        ? parseRawLines(parsed.crosses)
        : [],
    };

    const total =
      result.carries.length + result.passes.length + result.crosses.length;
    logInfo(
      `  Vision: carries ${result.carries.length}개, passes ${result.passes.length}개, crosses ${result.crosses.length}개 (총 ${total}개)`,
    );
    return result;
  } catch (error) {
    logError(
      `Vision API 호출 실패: ${error instanceof Error ? error.message : "unknown"}`,
      error instanceof Error ? error : undefined,
    );
    return emptyResult;
  }
}

/** 이미지 URL에서 Buffer 다운로드 */
export async function downloadImage(url: string): Promise<Buffer | null> {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      logError(`이미지 다운로드 실패: ${response.status} ${url}`, null);
      return null;
    }
    return Buffer.from(await response.arrayBuffer());
  } catch (error) {
    logError(
      `이미지 다운로드 오류: ${url}`,
      error instanceof Error ? error : undefined,
    );
    return null;
  }
}

/** 추출 결과 요약 로그 */
export function logExtractionSummary(
  actionType: string,
  extracted: number,
  totalCount: number,
): void {
  const ratio = totalCount > 0 ? Math.round((extracted / totalCount) * 100) : 0;
  const status = ratio >= 70 ? "good" : ratio >= 40 ? "fair" : "poor";
  logInfo(
    `  ${actionType}: ${extracted}/${totalCount}개 추출 (${ratio}%) [${status}]`,
  );
}
