// Claude Vision API로 Action Map PNG에서 올챙이(tadpole) 좌표 추출

import { getAnthropicClient } from "./anthropic-client";
import { logError, logInfo, logWarn } from "./logger";
import type { ParsedActionLine } from "./types";
import { waitForVisionSlot } from "./vision-rate-limiter";

/** Vision API 응답에서 파싱할 단일 라인 */
interface RawVisionLine {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  color: "pink" | "mint" | "black";
  circle_size?: "small" | "medium" | "large";
}

/** Vision API 응답 스키마 */
interface VisionResponse {
  lines: RawVisionLine[];
}

/** 피치 좌표 유효성 검증 */
function isValidCoordinate(x: number, y: number): boolean {
  return x >= 0 && x <= 105 && y >= 0 && y <= 68;
}

/** circle_size → xT 근사값 매핑 */
function circleToXt(size?: "small" | "medium" | "large"): number | undefined {
  switch (size) {
    case "large":
      return 0.05;
    case "medium":
      return 0.025;
    case "small":
      return 0.01;
    default:
      return undefined;
  }
}

/** 프롬프트 생성 */
function buildPrompt(actionType: "carries" | "passes" | "crosses"): string {
  return `You are analyzing a football (soccer) action map image generated by ScoutLab.
The image shows a football pitch from a top-down view with "tadpole" shapes representing ${actionType}.

## Pitch Coordinate System
- The pitch is 105m x 68m
- Bottom-left corner = (0, 0), top-right corner = (105, 68)
- The left goal line is at x=0, right goal line at x=105
- Bottom touchline at y=0, top touchline at y=68

## Landmark Anchors (use these to calibrate coordinates)
- Center circle: center at (52.5, 34), radius ~9.15m
- Left penalty box: x=0 to x=16.5, y=13.84 to y=54.16
- Right penalty box: x=88.5 to x=105, y=13.84 to y=54.16
- Left 6-yard box: x=0 to x=5.5, y=24.84 to y=43.16
- Right 6-yard box: x=99.5 to x=105, y=24.84 to y=43.16
- Penalty spots: (11, 34) and (94, 34)

## Tadpole Structure
Each tadpole consists of:
1. A LINE: thick end = start point (ball origin), thin end = end point (ball destination)
2. A CIRCLE at the start point: size proportional to xT (expected threat) value

## Color Classification
- PINK/MAGENTA lines = "progressive" (forward-moving actions)
- MINT/CYAN/TEAL lines = "threatening" (xT > 0.02)
- BLACK/DARK GRAY lines = regular (neither progressive nor threatening)

## Task
Extract ALL visible tadpole lines from this image. For each:
1. Estimate start (x1,y1) and end (x2,y2) coordinates in pitch meters
2. Classify the color as "pink", "mint", or "black"
3. Estimate the circle size as "small", "medium", or "large"

Round coordinates to 1 decimal place.

Respond with ONLY valid JSON in this exact format (no markdown, no explanation):
{"lines":[{"x1":30.5,"y1":45.2,"x2":55.0,"y2":40.1,"color":"pink","circle_size":"medium"}]}

If you cannot identify any tadpoles, respond: {"lines":[]}`;
}

/** PNG Buffer → Vision API → ParsedActionLine[] */
export async function extractActionLinesFromImage(
  imageBuffer: Buffer,
  actionType: "carries" | "passes" | "crosses",
): Promise<ParsedActionLine[]> {
  const client = getAnthropicClient();
  const base64 = imageBuffer.toString("base64");

  await waitForVisionSlot();

  try {
    const response = await client.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 4096,
      messages: [
        {
          role: "user",
          content: [
            {
              type: "image",
              source: {
                type: "base64",
                media_type: "image/png",
                data: base64,
              },
            },
            {
              type: "text",
              text: buildPrompt(actionType),
            },
          ],
        },
      ],
    });

    // 텍스트 응답 추출
    const textBlock = response.content.find((b) => b.type === "text");
    if (!textBlock || textBlock.type !== "text") {
      logWarn(`Vision API 응답에 텍스트 블록 없음`);
      return [];
    }

    // JSON 파싱
    const rawText = textBlock.text.trim();
    let parsed: VisionResponse;
    try {
      parsed = JSON.parse(rawText) as VisionResponse;
    } catch {
      // JSON 블록이 마크다운 코드블록 안에 있을 수 있음
      const jsonMatch = rawText.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        parsed = JSON.parse(jsonMatch[0]) as VisionResponse;
      } else {
        logError(
          `Vision API 응답 JSON 파싱 실패: ${rawText.slice(0, 200)}`,
          null,
        );
        return [];
      }
    }

    if (!Array.isArray(parsed.lines)) {
      logWarn(`Vision API 응답에 lines 배열 없음`);
      return [];
    }

    // 좌표 변환 + 유효성 검증
    const validLines: ParsedActionLine[] = [];
    for (const line of parsed.lines) {
      if (
        typeof line.x1 !== "number" ||
        typeof line.y1 !== "number" ||
        typeof line.x2 !== "number" ||
        typeof line.y2 !== "number"
      ) {
        continue;
      }

      if (
        !isValidCoordinate(line.x1, line.y1) ||
        !isValidCoordinate(line.x2, line.y2)
      ) {
        continue;
      }

      validLines.push({
        x1: Math.round(line.x1 * 10) / 10,
        y1: Math.round(line.y1 * 10) / 10,
        x2: Math.round(line.x2 * 10) / 10,
        y2: Math.round(line.y2 * 10) / 10,
        progressive: line.color === "pink",
        threatening: line.color === "mint",
        xt: circleToXt(line.circle_size),
      });
    }

    return validLines;
  } catch (error) {
    logError(
      `Vision API 호출 실패: ${error instanceof Error ? error.message : "unknown"}`,
      error instanceof Error ? error : undefined,
    );
    return [];
  }
}

/** 이미지 URL에서 Buffer 다운로드 */
export async function downloadImage(url: string): Promise<Buffer | null> {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      logError(`이미지 다운로드 실패: ${response.status} ${url}`, null);
      return null;
    }
    return Buffer.from(await response.arrayBuffer());
  } catch (error) {
    logError(
      `이미지 다운로드 오류: ${url}`,
      error instanceof Error ? error : undefined,
    );
    return null;
  }
}

/** 추출 결과 요약 로그 */
export function logExtractionSummary(
  actionType: string,
  extracted: number,
  totalCount: number,
): void {
  const ratio = totalCount > 0 ? Math.round((extracted / totalCount) * 100) : 0;
  const status = ratio >= 70 ? "good" : ratio >= 40 ? "fair" : "poor";
  logInfo(
    `  ${actionType}: ${extracted}/${totalCount}개 추출 (${ratio}%) [${status}]`,
  );
}
